name: Multi-Module CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      
      - name: package
        run: |
          mvn clean package

      - name: jdeps
        run: |
          jdeps -cp ~/.m2/repository/com/blazebit/blaze-persistence-integration-hibernate-6.2/1.6.15/blaze-persistence-integration-hibernate-6.2-1.6.15.jar \
          --verbose:class | grep OracleUserDefinedTypeExporter
      
      # - name: Build Module
      #   run: |
      #     mvn package -Pnative -Dquarkus.native.container-build=true -DskipTests 
