name: Multi-Module CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Compile
        run: |
          mvn clean compile -DskipTests
      
      - name: Build Module
        run: |
          mvn package -Pnative -Dquarkus.native.container-build=true -DskipTests \
          -Dquarkus.native.additional-build-args=--initialize-at-build-time=org.hibernate.dialect.OracleUserDefinedTypeExporter
